export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET';

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST';
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL';
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET';

export const USER_CHANGE_PASSWORD_REQUEST = 'USER_CHANGE_PASSWORD_REQUEST';
export const USER_CHANGE_PASSWORD_SUCCESS = 'USER_CHANGE_PASSWORD_SUCCESS';
export const USER_CHANGE_PASSWORD_FAIL = 'USER_CHANGE_PASSWORD_FAIL';
export const USER_CHANGE_PASSWORD_RESET = 'USER_CHANGE_PASSWORD_RESET';

export const ADDRESS_LIST_REQUEST = 'ADDRESS_LIST_REQUEST';
export const ADDRESS_LIST_SUCCESS = 'ADDRESS_LIST_SUCCESS';
export const ADDRESS_LIST_FAIL = 'ADDRESS_LIST_FAIL';

export const ADDRESS_DETAILS_REQUEST = 'ADDRESS_DETAILS_REQUEST';
export const ADDRESS_DETAILS_SUCCESS = 'ADDRESS_DETAILS_SUCCESS';
export const ADDRESS_DETAILS_FAIL = 'ADDRESS_DETAILS_FAIL';
export const ADDRESS_DETAILS_RESET = 'ADDRESS_DETAILS_RESET';

export const ADDRESS_CREATE_REQUEST = 'ADDRESS_CREATE_REQUEST';
export const ADDRESS_CREATE_SUCCESS = 'ADDRESS_CREATE_SUCCESS';
export const ADDRESS_CREATE_FAIL = 'ADDRESS_CREATE_FAIL';
export const ADDRESS_CREATE_RESET = 'ADDRESS_CREATE_RESET';

export const ADDRESS_UPDATE_REQUEST = 'ADDRESS_UPDATE_REQUEST';
export const ADDRESS_UPDATE_SUCCESS = 'ADDRESS_UPDATE_SUCCESS';
export const ADDRESS_UPDATE_FAIL = 'ADDRESS_UPDATE_FAIL';
export const ADDRESS_UPDATE_RESET = 'ADDRESS_UPDATE_RESET';

export const ADDRESS_DELETE_REQUEST = 'ADDRESS_DELETE_REQUEST';
export const ADDRESS_DELETE_SUCCESS = 'ADDRESS_DELETE_SUCCESS';
export const ADDRESS_DELETE_FAIL = 'ADDRESS_DELETE_FAIL';

export const ADDRESS_SET_DEFAULT_REQUEST = 'ADDRESS_SET_DEFAULT_REQUEST';
export const ADDRESS_SET_DEFAULT_SUCCESS = 'ADDRESS_SET_DEFAULT_SUCCESS';
export const ADDRESS_SET_DEFAULT_FAIL = 'ADDRESS_SET_DEFAULT_FAIL';

export const LOYALTY_POINTS_ADD_REQUEST = 'LOYALTY_POINTS_ADD_REQUEST';
export const LOYALTY_POINTS_ADD_SUCCESS = 'LOYALTY_POINTS_ADD_SUCCESS';
export const LOYALTY_POINTS_ADD_FAIL = 'LOYALTY_POINTS_ADD_FAIL';


// Password reset request constants
export const PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_FAIL = 'PASSWORD_RESET_FAIL';
export const PASSWORD_RESET_RESET = 'PASSWORD_RESET_RESET';

// Password reset code verify constants
export const PASSWORD_RESET_VERIFY_REQUEST = 'PASSWORD_RESET_VERIFY_REQUEST';
export const PASSWORD_RESET_VERIFY_SUCCESS = 'PASSWORD_RESET_VERIFY_SUCCESS';
export const PASSWORD_RESET_VERIFY_FAIL = 'PASSWORD_RESET_VERIFY_FAIL';
export const PASSWORD_RESET_VERIFY_RESET = 'PASSWORD_RESET_VERIFY_RESET';

// Password reset confirm constants
export const PASSWORD_RESET_CONFIRM_REQUEST = 'PASSWORD_RESET_CONFIRM_REQUEST';
export const PASSWORD_RESET_CONFIRM_SUCCESS = 'PASSWORD_RESET_CONFIRM_SUCCESS';
export const PASSWORD_RESET_CONFIRM_FAIL = 'PASSWORD_RESET_CONFIRM_FAIL';
export const PASSWORD_RESET_CONFIRM_RESET = 'PASSWORD_RESET_CONFIRM_RESET';