export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET';

export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST';
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL';
export const ORDER_LIST_RESET = 'ORDER_LIST_RESET';

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';
export const ORDER_DETAILS_RESET = 'ORDER_DETAILS_RESET';

export const MY_ORDERS_REQUEST = 'MY_ORDERS_REQUEST';
export const MY_ORDERS_SUCCESS = 'MY_ORDERS_SUCCESS';
export const MY_ORDERS_FAIL = 'MY_ORDERS_FAIL';

export const ORDER_UPDATE_STATUS_REQUEST = 'ORDER_UPDATE_STATUS_REQUEST';
export const ORDER_UPDATE_STATUS_SUCCESS = 'ORDER_UPDATE_STATUS_SUCCESS';
export const ORDER_UPDATE_STATUS_FAIL = 'ORDER_UPDATE_STATUS_FAIL';

export const ORDER_CANCEL_REQUEST = 'ORDER_CANCEL_REQUEST';
export const ORDER_CANCEL_SUCCESS = 'ORDER_CANCEL_SUCCESS';
export const ORDER_CANCEL_FAIL = 'ORDER_CANCEL_FAIL';

export const ORDER_ADD_TRACKING_REQUEST = 'ORDER_ADD_TRACKING_REQUEST';
export const ORDER_ADD_TRACKING_SUCCESS = 'ORDER_ADD_TRACKING_SUCCESS';
export const ORDER_ADD_TRACKING_FAIL = 'ORDER_ADD_TRACKING_FAIL';

export const ORDER_TRACKING_INFO_REQUEST = 'ORDER_TRACKING_INFO_REQUEST';
export const ORDER_TRACKING_INFO_SUCCESS = 'ORDER_TRACKING_INFO_SUCCESS';
export const ORDER_TRACKING_INFO_FAIL = 'ORDER_TRACKING_INFO_FAIL';

export const ORDER_RETURN_CREATE_REQUEST = 'ORDER_RETURN_CREATE_REQUEST';
export const ORDER_RETURN_CREATE_SUCCESS = 'ORDER_RETURN_CREATE_SUCCESS';
export const ORDER_RETURN_CREATE_FAIL = 'ORDER_RETURN_CREATE_FAIL';

export const ORDER_RETURN_LIST_REQUEST = 'ORDER_RETURN_LIST_REQUEST';
export const ORDER_RETURN_LIST_SUCCESS = 'ORDER_RETURN_LIST_SUCCESS';
export const ORDER_RETURN_LIST_FAIL = 'ORDER_RETURN_LIST_FAIL';

export const SHIPPING_METHODS_REQUEST = 'SHIPPING_METHODS_REQUEST';
export const SHIPPING_METHODS_SUCCESS = 'SHIPPING_METHODS_SUCCESS';
export const SHIPPING_METHODS_FAIL = 'SHIPPING_METHODS_FAIL';

export const SHIPPING_QUOTE_REQUEST = 'SHIPPING_QUOTE_REQUEST';
export const SHIPPING_QUOTE_SUCCESS = 'SHIPPING_QUOTE_SUCCESS';
export const SHIPPING_QUOTE_FAIL = 'SHIPPING_QUOTE_FAIL';

export const ORDER_ANALYTICS_REQUEST = 'ORDER_ANALYTICS_REQUEST';
export const ORDER_ANALYTICS_SUCCESS = 'ORDER_ANALYTICS_SUCCESS';
export const ORDER_ANALYTICS_FAIL = 'ORDER_ANALYTICS_FAIL';

export const PUBLIC_ORDER_STATUS_REQUEST = 'PUBLIC_ORDER_STATUS_REQUEST';
export const PUBLIC_ORDER_STATUS_SUCCESS = 'PUBLIC_ORDER_STATUS_SUCCESS';
export const PUBLIC_ORDER_STATUS_FAIL = 'PUBLIC_ORDER_STATUS_FAIL';

export const ORDER_EXPORT_REQUEST = 'ORDER_EXPORT_REQUEST';
export const ORDER_EXPORT_SUCCESS = 'ORDER_EXPORT_SUCCESS';
export const ORDER_EXPORT_FAIL = 'ORDER_EXPORT_FAIL';

export const ORDER_ITEM_DOWNLOAD_REQUEST = 'ORDER_ITEM_DOWNLOAD_REQUEST';
export const ORDER_ITEM_DOWNLOAD_SUCCESS = 'ORDER_ITEM_DOWNLOAD_SUCCESS';
export const ORDER_ITEM_DOWNLOAD_FAIL = 'ORDER_ITEM_DOWNLOAD_FAIL';

export const ORDER_NOTE_CREATE_REQUEST = 'ORDER_NOTE_CREATE_REQUEST';
export const ORDER_NOTE_CREATE_SUCCESS = 'ORDER_NOTE_CREATE_SUCCESS';
export const ORDER_NOTE_CREATE_FAIL = 'ORDER_NOTE_CREATE_FAIL';

export const ORDER_NOTE_LIST_REQUEST = 'ORDER_NOTE_LIST_REQUEST';
export const ORDER_NOTE_LIST_SUCCESS = 'ORDER_NOTE_LIST_SUCCESS';
export const ORDER_NOTE_LIST_FAIL = 'ORDER_NOTE_LIST_FAIL';

// Filter constants
export const SET_ORDER_FILTERS = 'SET_ORDER_FILTERS';
export const CLEAR_ORDER_FILTERS = 'CLEAR_ORDER_FILTERS';
export const SET_ORDER_SORT = 'SET_ORDER_SORT';