// Product List
export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

// Product Details
export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';
export const PRODUCT_DETAILS_RESET = 'PRODUCT_DETAILS_RESET';

// Featured Products
export const FEATURED_PRODUCTS_REQUEST = 'FEATURED_PRODUCTS_REQUEST';
export const FEATURED_PRODUCTS_SUCCESS = 'FEATURED_PRODUCTS_SUCCESS';
export const FEATURED_PRODUCTS_FAIL = 'FEATURED_PRODUCTS_FAIL';

// On Sale Products
export const ON_SALE_PRODUCTS_REQUEST = 'ON_SALE_PRODUCTS_REQUEST';
export const ON_SALE_PRODUCTS_SUCCESS = 'ON_SALE_PRODUCTS_SUCCESS';
export const ON_SALE_PRODUCTS_FAIL = 'ON_SALE_PRODUCTS_FAIL';

// New Arrival Products
export const NEW_ARRIVAL_PRODUCTS_REQUEST = 'NEW_ARRIVAL_PRODUCTS_REQUEST';
export const NEW_ARRIVAL_PRODUCTS_SUCCESS = 'NEW_ARRIVAL_PRODUCTS_SUCCESS';
export const NEW_ARRIVAL_PRODUCTS_FAIL = 'NEW_ARRIVAL_PRODUCTS_FAIL';

// Bestseller Products
export const BESTSELLER_PRODUCTS_REQUEST = 'BESTSELLER_PRODUCTS_REQUEST';
export const BESTSELLER_PRODUCTS_SUCCESS = 'BESTSELLER_PRODUCTS_SUCCESS';
export const BESTSELLER_PRODUCTS_FAIL = 'BESTSELLER_PRODUCTS_FAIL';

// Category List
export const CATEGORY_LIST_REQUEST = 'CATEGORY_LIST_REQUEST';
export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS';
export const CATEGORY_LIST_FAIL = 'CATEGORY_LIST_FAIL';

// Category Details
export const CATEGORY_DETAILS_REQUEST = 'CATEGORY_DETAILS_REQUEST';
export const CATEGORY_DETAILS_SUCCESS = 'CATEGORY_DETAILS_SUCCESS';
export const CATEGORY_DETAILS_FAIL = 'CATEGORY_DETAILS_FAIL';

// Category Products
export const CATEGORY_PRODUCTS_REQUEST = 'CATEGORY_PRODUCTS_REQUEST';
export const CATEGORY_PRODUCTS_SUCCESS = 'CATEGORY_PRODUCTS_SUCCESS';
export const CATEGORY_PRODUCTS_FAIL = 'CATEGORY_PRODUCTS_FAIL';

// Category Create
export const CATEGORY_CREATE_REQUEST = 'CATEGORY_CREATE_REQUEST';
export const CATEGORY_CREATE_SUCCESS = 'CATEGORY_CREATE_SUCCESS';
export const CATEGORY_CREATE_FAIL = 'CATEGORY_CREATE_FAIL';
export const CATEGORY_CREATE_RESET = 'CATEGORY_CREATE_RESET';

// Category Update
export const CATEGORY_UPDATE_REQUEST = 'CATEGORY_UPDATE_REQUEST';
export const CATEGORY_UPDATE_SUCCESS = 'CATEGORY_UPDATE_SUCCESS';
export const CATEGORY_UPDATE_FAIL = 'CATEGORY_UPDATE_FAIL';
export const CATEGORY_UPDATE_RESET = 'CATEGORY_UPDATE_RESET';

// Category Delete
export const CATEGORY_DELETE_REQUEST = 'CATEGORY_DELETE_REQUEST';
export const CATEGORY_DELETE_SUCCESS = 'CATEGORY_DELETE_SUCCESS';
export const CATEGORY_DELETE_FAIL = 'CATEGORY_DELETE_FAIL';

// Brand List
export const BRAND_LIST_REQUEST = 'BRAND_LIST_REQUEST';
export const BRAND_LIST_SUCCESS = 'BRAND_LIST_SUCCESS';
export const BRAND_LIST_FAIL = 'BRAND_LIST_FAIL';

// Brand Details
export const BRAND_DETAILS_REQUEST = 'BRAND_DETAILS_REQUEST';
export const BRAND_DETAILS_SUCCESS = 'BRAND_DETAILS_SUCCESS';
export const BRAND_DETAILS_FAIL = 'BRAND_DETAILS_FAIL';

// Brand Products
export const BRAND_PRODUCTS_REQUEST = 'BRAND_PRODUCTS_REQUEST';
export const BRAND_PRODUCTS_SUCCESS = 'BRAND_PRODUCTS_SUCCESS';
export const BRAND_PRODUCTS_FAIL = 'BRAND_PRODUCTS_FAIL';

// Brand Create
export const BRAND_CREATE_REQUEST = 'BRAND_CREATE_REQUEST';
export const BRAND_CREATE_SUCCESS = 'BRAND_CREATE_SUCCESS';
export const BRAND_CREATE_FAIL = 'BRAND_CREATE_FAIL';
export const BRAND_CREATE_RESET = 'BRAND_CREATE_RESET';

// Brand Update
export const BRAND_UPDATE_REQUEST = 'BRAND_UPDATE_REQUEST';
export const BRAND_UPDATE_SUCCESS = 'BRAND_UPDATE_SUCCESS';
export const BRAND_UPDATE_FAIL = 'BRAND_UPDATE_FAIL';
export const BRAND_UPDATE_RESET = 'BRAND_UPDATE_RESET';

// Brand Delete
export const BRAND_DELETE_REQUEST = 'BRAND_DELETE_REQUEST';
export const BRAND_DELETE_SUCCESS = 'BRAND_DELETE_SUCCESS';
export const BRAND_DELETE_FAIL = 'BRAND_DELETE_FAIL';

// Review List
export const REVIEW_LIST_REQUEST = 'REVIEW_LIST_REQUEST';
export const REVIEW_LIST_SUCCESS = 'REVIEW_LIST_SUCCESS';
export const REVIEW_LIST_FAIL = 'REVIEW_LIST_FAIL';

// Review Create
export const REVIEW_CREATE_REQUEST = 'REVIEW_CREATE_REQUEST';
export const REVIEW_CREATE_SUCCESS = 'REVIEW_CREATE_SUCCESS';
export const REVIEW_CREATE_FAIL = 'REVIEW_CREATE_FAIL';
export const REVIEW_CREATE_RESET = 'REVIEW_CREATE_RESET';

// Review Update
export const REVIEW_UPDATE_REQUEST = 'REVIEW_UPDATE_REQUEST';
export const REVIEW_UPDATE_SUCCESS = 'REVIEW_UPDATE_SUCCESS';
export const REVIEW_UPDATE_FAIL = 'REVIEW_UPDATE_FAIL';
export const REVIEW_UPDATE_RESET = 'REVIEW_UPDATE_RESET';

// Review Delete
export const REVIEW_DELETE_REQUEST = 'REVIEW_DELETE_REQUEST';
export const REVIEW_DELETE_SUCCESS = 'REVIEW_DELETE_SUCCESS';
export const REVIEW_DELETE_FAIL = 'REVIEW_DELETE_FAIL';

// My Reviews
export const MY_REVIEWS_REQUEST = 'MY_REVIEWS_REQUEST';
export const MY_REVIEWS_SUCCESS = 'MY_REVIEWS_SUCCESS';
export const MY_REVIEWS_FAIL = 'MY_REVIEWS_FAIL';

// Review Mark Helpful
export const REVIEW_MARK_HELPFUL_REQUEST = 'REVIEW_MARK_HELPFUL_REQUEST';
export const REVIEW_MARK_HELPFUL_SUCCESS = 'REVIEW_MARK_HELPFUL_SUCCESS';
export const REVIEW_MARK_HELPFUL_FAIL = 'REVIEW_MARK_HELPFUL_FAIL';

// Product Image Add
export const PRODUCT_IMAGE_ADD_REQUEST = 'PRODUCT_IMAGE_ADD_REQUEST';
export const PRODUCT_IMAGE_ADD_SUCCESS = 'PRODUCT_IMAGE_ADD_SUCCESS';
export const PRODUCT_IMAGE_ADD_FAIL = 'PRODUCT_IMAGE_ADD_FAIL';

// Product Image Delete
export const PRODUCT_IMAGE_DELETE_REQUEST = 'PRODUCT_IMAGE_DELETE_REQUEST';
export const PRODUCT_IMAGE_DELETE_SUCCESS = 'PRODUCT_IMAGE_DELETE_SUCCESS';
export const PRODUCT_IMAGE_DELETE_FAIL = 'PRODUCT_IMAGE_DELETE_FAIL';

// Product Image Update
export const PRODUCT_IMAGE_UPDATE_REQUEST = 'PRODUCT_IMAGE_UPDATE_REQUEST';
export const PRODUCT_IMAGE_UPDATE_SUCCESS = 'PRODUCT_IMAGE_UPDATE_SUCCESS';
export const PRODUCT_IMAGE_UPDATE_FAIL = 'PRODUCT_IMAGE_UPDATE_FAIL';

// Product Create
export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST';
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS';
export const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL';
export const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET';

// Product Update
export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST';
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS';
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL';
export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET';

// Product Delete
export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL';

// Product Increment View
export const PRODUCT_INCREMENT_VIEW_REQUEST = 'PRODUCT_INCREMENT_VIEW_REQUEST';
export const PRODUCT_INCREMENT_VIEW_SUCCESS = 'PRODUCT_INCREMENT_VIEW_SUCCESS';
export const PRODUCT_INCREMENT_VIEW_FAIL = 'PRODUCT_INCREMENT_VIEW_FAIL';

// Related Products
export const RELATED_PRODUCTS_REQUEST = 'RELATED_PRODUCTS_REQUEST';
export const RELATED_PRODUCTS_SUCCESS = 'RELATED_PRODUCTS_SUCCESS';
export const RELATED_PRODUCTS_FAIL = 'RELATED_PRODUCTS_FAIL';

// Search Products
export const SEARCH_PRODUCTS_REQUEST = 'SEARCH_PRODUCTS_REQUEST';
export const SEARCH_PRODUCTS_SUCCESS = 'SEARCH_PRODUCTS_SUCCESS';
export const SEARCH_PRODUCTS_FAIL = 'SEARCH_PRODUCTS_FAIL';
export const SEARCH_PRODUCTS_RESET = 'SEARCH_PRODUCTS_RESET';

// Filters
export const SET_FILTERS = 'SET_FILTERS';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';
export const SET_SORT = 'SET_SORT';
export const SET_PRICE_RANGE = 'SET_PRICE_RANGE';
export const SET_CATEGORY_FILTER = 'SET_CATEGORY_FILTER';
export const SET_BRAND_FILTER = 'SET_BRAND_FILTER';
export const SET_RATING_FILTER = 'SET_RATING_FILTER';
export const TOGGLE_IN_STOCK_FILTER = 'TOGGLE_IN_STOCK_FILTER';
export const TOGGLE_ON_SALE_FILTER = 'TOGGLE_ON_SALE_FILTER';