export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';
export const PRODUCT_DETAILS_RESET = 'PRODUCT_DETAILS_RESET';

export const CATEGORY_LIST_REQUEST = 'CATEGORY_LIST_REQUEST';
export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS';
export const CATEGORY_LIST_FAIL = 'CATEGORY_LIST_FAIL';

export const BRAND_LIST_REQUEST = 'BRAND_LIST_REQUEST';
export const BRAND_LIST_SUCCESS = 'BRAND_LIST_SUCCESS';
export const BRAND_LIST_FAIL = 'BRAND_LIST_FAIL';

export const SET_FILTERS = 'SET_FILTERS';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';
export const SET_SORT = 'SET_SORT';

export const REVIEW_CREATE_REQUEST = 'REVIEW_CREATE_REQUEST';
export const REVIEW_CREATE_SUCCESS = 'REVIEW_CREATE_SUCCESS';
export const REVIEW_CREATE_FAIL = 'REVIEW_CREATE_FAIL';
export const REVIEW_CREATE_RESET = 'REVIEW_CREATE_RESET';


// Featured Products
export const FEATURED_PRODUCTS_REQUEST = 'FEATURED_PRODUCTS_REQUEST';
export const FEATURED_PRODUCTS_SUCCESS = 'FEATURED_PRODUCTS_SUCCESS';
export const FEATURED_PRODUCTS_FAIL = 'FEATURED_PRODUCTS_FAIL';

// On Sale Products
export const ON_SALE_PRODUCTS_REQUEST = 'ON_SALE_PRODUCTS_REQUEST';
export const ON_SALE_PRODUCTS_SUCCESS = 'ON_SALE_PRODUCTS_SUCCESS';
export const ON_SALE_PRODUCTS_FAIL = 'ON_SALE_PRODUCTS_FAIL';

// Category Products
export const CATEGORY_PRODUCTS_REQUEST = 'CATEGORY_PRODUCTS_REQUEST';
export const CATEGORY_PRODUCTS_SUCCESS = 'CATEGORY_PRODUCTS_SUCCESS';
export const CATEGORY_PRODUCTS_FAIL = 'CATEGORY_PRODUCTS_FAIL';


// Brand Products
export const BRAND_PRODUCTS_REQUEST = 'BRAND_PRODUCTS_REQUEST';
export const BRAND_PRODUCTS_SUCCESS = 'BRAND_PRODUCTS_SUCCESS';
export const BRAND_PRODUCTS_FAIL = 'BRAND_PRODUCTS_FAIL';

// Reviews
export const REVIEW_LIST_REQUEST = 'REVIEW_LIST_REQUEST';
export const REVIEW_LIST_SUCCESS = 'REVIEW_LIST_SUCCESS';
export const REVIEW_LIST_FAIL = 'REVIEW_LIST_FAIL';

export const MY_REVIEWS_REQUEST = 'MY_REVIEWS_REQUEST';
export const MY_REVIEWS_SUCCESS = 'MY_REVIEWS_SUCCESS';
export const MY_REVIEWS_FAIL = 'MY_REVIEWS_FAIL';

// Product Images
export const PRODUCT_IMAGE_ADD_REQUEST = 'PRODUCT_IMAGE_ADD_REQUEST';
export const PRODUCT_IMAGE_ADD_SUCCESS = 'PRODUCT_IMAGE_ADD_SUCCESS';
export const PRODUCT_IMAGE_ADD_FAIL = 'PRODUCT_IMAGE_ADD_FAIL';

export const PRODUCT_IMAGE_DELETE_REQUEST = 'PRODUCT_IMAGE_DELETE_REQUEST';
export const PRODUCT_IMAGE_DELETE_SUCCESS = 'PRODUCT_IMAGE_DELETE_SUCCESS';
export const PRODUCT_IMAGE_DELETE_FAIL = 'PRODUCT_IMAGE_DELETE_FAIL';
